apiVersion: v1
kind: Service
metadata:
  name: {{ include "opsconsole.fullname" . }}-frontend
  labels:
    {{- include "opsconsole.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    {{- include "opsconsole.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.port }}
      targetPort: http
      protocol: TCP
