{{- if not .Values.backend.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opsconsole.fullname" . }}-backend
  labels:
    {{- include "opsconsole.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
stringData:
  OPS_JWT_SECRET: {{ .Values.backend.secret.OPS_JWT_SECRET | quote }}
  OPS_DATABASE_URL: {{ .Values.backend.secret.OPS_DATABASE_URL | quote }}
  OPS_GITLAB_TOKEN: {{ .Values.backend.secret.OPS_GITLAB_TOKEN | quote }}
  OPS_KUBECONFIG: {{ .Values.backend.secret.OPS_KUBECONFIG | quote }}
{{- end }}
